name: shopping_app
description: A shopping app (allegro copy)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  provider: ^6.0.3
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  google_sign_in: ^5.4.2
  flutter_launcher_icons: ^0.10.0
  rflutter_alert: ^2.0.4
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.10
  cloud_firestore: ^3.5.0
  carousel_slider: ^4.1.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-Regular.ttf
        - asset: assets/fonts/Overpass-Bold.ttf
          weight: 600